services:
  - type: web
    name: SIH-1669
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000